# RCA  Universal Remote. Lame.  Uses both TV &  DVD mode for these codes
# TV code: 01618,  DVD/BlueRay code:  36352
PWR:0x2                 # Quit program
REW:0x47                # Seek backward in video
FWD:0x15                # Seek forward in video
PLAY_NEXT:0x46          # Play next video
PLAY_PREV:0x16          # Play previous video
PLAY_PAUSE:0x55         # Pause/play
PLAY_PSE:0x45           # Pause/play
SPEED+:0x1b             # Increase playback speed
SPEED-:0x1f             # Decrease playback speed
VOL+:0xf                # Increase volume
VOL-:0x4b               # Decrease volume
MUTE-UNMUTE:0x49        # Mute/unmute
LOOP:0x40               # Loop single video
SCREENSHOT:0x5a         # Screenshot
SCRNSHOT:0x5a           # Screenshot
RESTART:0x11            # Restart video to beginning
MENU:0x44               # Menu - Remote control Help box
HUD:0x54		        # Square key to left of the zero button.  Brings up the HUD.
1:0x1                   # 1 button - Toggle OSD (3 states)
#2:0x2                  # 2 button - Conflicts with PWR
3:0x3                   # 3 button - Save Playlist
4:0x4                   # 4 button - Print Playlist
5:0x5                   # 5 button - Randomize Playlist
6:0x6                   # 6 button - Show metadata info
7:0x7                   # 7 button - Toggle video title (3 states)
8:0x8                   # 8 button - Stub_1
9:0x9                   # 9 button - Stub_2
0:0x0                   # 0 button - Stub_3
