GE Universal Remote. Use the DVD mode for these codes

PWR:0x2                 # Quit program
REW:0x1e                # Seek backward in video
FWD:0x1c                # Seek forward in video
PLAY_NEXT:0x1d          # Play next video
PLAY_PREV:0x13          # Play previous video
PLAY_PAUSE:0xb          # Pause/play
SPEED+:0x1f             # Increase playback speed
SPEED-:0x40             # Decrease playback speed
VOL+:0x4c               # Increase volume
VOL-:0x54               # Decrease volume
MUTE-UNMUTE:0x4         # Mute/unmute
LOOP:0x16               # Loop single video
SCREENSHOT:0x19         # Screenshot
SCRNSHOT:0x58           # Screenshot
RESTART:0x18            # Restart video to beginning
MENU:0x1a               # Menu - Remote control Help box
1:0xa                   # 1 button - Toggle OSD (3 states)
2:0x9                   # 2 button - Toggle video title (3 states)
3:0x8                   # 3 button - Save Playlist
4:0x12                  # 4 button - Randomize Playlist
5:0x11                  # 5 button - Show metadata info
6:0x10                  # 6 button - Toggle Interpolation (3 states)
7:0xe                   # 7 button - Toggle Greyscale
